### ISSUE TITLE
Lexer does not properly handle alternatives

### ISSUE THREAD

**Issue by Olivki** [jukkas-lang/jukkas#14]
The way the lexer handles alternatives is fundamentally different from how JFlex handled things, and it needs to be fixed to make using our custom lexer even remotely idiomatic.

An example of a problem is for how we're matching for integer literals, the flex code was structured like this:
```lex
Digit = [0-9]
DigitOrUnderscore = [_0-9]
HexDigit = [0-9A-Fa-f]
HexDigitOrUnderscore = [_0-9A-Fa-f]

IntegerLiteral = {DecimalIntegerLiteral} | {HexIntegerLiteral} | {BinIntegerLiteral}
DecimalIntegerLiteral = (0 | ([1-9]({DigitOrUnderscore})*))
HexIntegerLiteral = 0[Xx]({HexDigitOrUnderscore})*
BinIntegerLiteral = 0[Bb]({DigitOrUnderscore})*
```

And our rules are currently structured like this:
```kotlin
private val decimalIntLiteral = regex("0|([1-9][0-9_]*)")
private val hexIntLiteral = regex("0[xX][_0-9A-Fa-f]+")
private val binIntLiteral = regex("0[bB][_01]+")
private val intLiteral = decimalIntLiteral or hexIntLiteral or binIntLiteral
```

Given the input `0b0101010101` the lexer *should* produce a segment containing `0b0101010101`, which JFlex does, but our lexer produces a segment containing only `0`. The cause of this issue can be easier shown by rewriting our rules to more clearly display what's actually going on:

```kotlin
private val zero = literal("0")
private val decimalIntLiteral = regex("([1-9][0-9_]*)")
private val hexIntLiteral = regex("0[xX][_0-9A-Fa-f]+")
private val binIntLiteral = regex("0[bB][_01]+")
private val intLiteral = zero or decimalIntLiteral or hexIntLiteral or binIntLiteral
```

Because our input contains `0`, our lexer sees `0` and just assumes that's all it needs. JFlex handles alternatives like this by never taking the shortest answer if a longer one can be matched, I can't find the exact documentation for it, but I know there should be some better explanation of it somewhere.

Our code *could* be changed to just work around this, but this is a fundamental issue in how our lexer works, and will most likely come and bite us in the ass if we don't fix it now.

The rules used to produce proper behavior for `or` operators in the lexer could also be extended to work with the `Matcher` operations, as our lexer rules now reside in an object, we could apply optimizations to to the rules it is given, which would also allow us to not worry about bugs popping up because we might have placed a rule in the wrong order.

In principle the resolution should go something like:
If we have two rules, matching on `foo` and `foobar`, and given the input `foobar`, the lexer should, without needing to care which *order* the rules were declared in, pick `foobar`, and not pick `foo`.

**Comment by Olivki** [comment]
Determining what part of a fragment to actually optimize might not be really doable just by using the standalone functions and operators, so we might need to introduce some function that takes a fragment and then applies optimizations/rules on it.

Something like 
```kotlin
private val intLiteral = fragment {
	zero or decimalIntLiteral or hexIntLiteral or binIntLiteral
}
```

Would probably look ok.

**Comment by ekgame** [comment]
The lexer has a "snapshot" system, where you can basically make a copy of the lexer state, try to match something and the either resume from that point or rollback to the previous state. At the moment, it's only used by the composite matcher to make sure two things are matched before moving on. This could be reused by the alternative matcher to take the longest match. This way the "or" operator itself should work as expected, without any additional layers of logic.

I don't really understand the idea for "optimizations" here. I'm sure there are more optimal ways to do the lexing than what we have now, but it shouldn't be a bottleneck for awhile.
